openapi: 3.0.0
info:
  title: Sample User API
  version: 1.0.0

paths:
  /users:
    get:
      summary: Get list of users
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK

  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
